services:
  flask-app:
    build: .
    container_name: flask-app
    environment:
      - OTEL_SERVICE_NAME=flask-app
      - OTEL_TRACES_EXPORTER=otlp,console
      - OTEL_METRICS_EXPORTER=otlp,console
      - OTEL_LOGS_EXPORTER=otlp,console
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://signoz-otel-collector:4318
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
    ports:
      - "5000:5000"
    networks:
    - signoz-net

networks:
  signoz-net:
    name: signoz-net
